### ISSUE TITLE
Runnnig UC.py without gurobi

### ISSUE THREAD

**Issue by Hilbertvp** [akxen/egrimod-nem#2]
Hey, 

First of all thanks for sharing these very useful scripts. It has taken me a couple of hours this morning to get everything to work and so I just wanted to share my experience.

Everything ran quite smoothly apart from UC.py. My main issue is with the gurobi solver. This is probably a great solver if you have an academic licence, but for people like myself who do not, it is not an option.  In DCOPF.py you can change over to gplk, but this fails in UC.py. Optimising with ipopt does seem to work though. 

Also it seems to be important here to have the specific pyomo version that is in the requirements (5.5.1). I has an later version and that threw an error.

Cheers,

**Comment by akxen** [comment]
Apologies for the late reply - thanks very much for taking an interest and sharing your experience! I recall running into issues when using GLPK to solve MILP problems in the past. Thanks for suggesting a workaround via IPOPT. I'll update the readme accordingly.

**Comment by akxen** [comment]
Will close this issue for now. Have referenced it in the updated readme.
